#ifndef EMULATOR_CONSTANTS_H
#define EMULATOR_CONSTANTS_H

#define NUM_REGISTERS 17
#define NUM_GEN_PURPOSE_REGISTERS 13
#define NUM_MEMORY_LOCATIONS 65536
#define WORD_SIZE 32
#define BYTE_SIZE 8
#define BYTES_PER_WORD 4
#define PC_INDEX 15
#define CPSR_INDEX 16

#endif
